#! /bin/bash

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

. /lib/services/init-functions

usage()
{
	echo "Usage: $0 {start|stop|restart} [ifupdown-options]"
	exit 1
}

[ $# -eq 0 ] && usage

do_start()
{
	log_daemon_msg "Configuring network interfaces" "ifup -a $@"
	ifup -a "$@"
	log_end_msg $?
}

do_stop()
{
	log_daemon_msg "Deconfiguring network interfaces" \
		"ifdown -a --exclude=lo $@"
	ifdown -a --exclude=lo "$@"
	log_end_msg $?
}

case "$1" in
start)
	do_start "${@:2}"
	;;
stop)
	do_stop "${@:2}"
	;;
restart)
	do_stop "${@:2}"
	do_start "${@:2}"
	;;
*)
	usage
	;;
esac

exit 0
